name: PR-Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
      issues: write

    steps:
      - name: PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CONFIG.MODEL: groq/llama-3.3-70b-versatile
          GROQ.KEY: ${{ secrets.GROQ_KEY }}
